# Default common configs
defaults:
  # Add common items
  - scenario_builder: nuplan
  - scenario_filter: filter_bos.yaml
  - model: null
  - autoencoder_model: null
  - diffusion_model: null
  # Worker that is used to run simulations
  - worker: ray_distributed

distribute_by_scenario: true
distributed_timeout_seconds: 7200 # Sets how long to wait while synchronizing across worker nodes in a distributed context.
selected_simulation_metrics: null

# Sets verbosity level, in particular determines if progress bars are shown or not.
verbose: false

##########################################################
# 确保 target_builder 使用你新写的名称
target_builder:
  - scenario_type  # 对应 get_feature_unique_name 返回的值